### ISSUE TITLE
Algorithms or Data-structures(any language)

### ISSUE THREAD

**Issue by anuragdevon** [anuragdevon/Data-Structures#1]
PR - Example: 
- Program Name - "yourProgramName" 

- Checks completed(self-Check)
 - [x]  File added in proper folder
 - [x]  File name is CamelCase(example - CircularLinkedList.py)
 - [ ]  Proper commenting done
 - [ ]  Clean code
 - [x]  I have performed a self-review of my own code

**Comment by ahmedashfaq027** [comment]
Hey, Can i add Tree Traversals in CPP?

**Comment by Anuragkar234** [comment]
> Hey, Can i add Tree Traversals in CPP?

Sure.

**Comment by karankeyash** [comment]
Which Data Structure exactly should we apply?

**Comment by mralanlee** [comment]
Can I add binary search in go and javascript?

**Comment by Anuragkar234** [comment]
> Which Data Structure exactly should we apply?

You can go for linear, linked, hash, etc as per you choice.

**Comment by ahmedashfaq027** [comment]
> > Hey, Can i add Tree Traversals in CPP?
> 
> Sure.
> create a PR, will verify and assign it

#2 Added TreeTraversals.cpp

**Comment by urjitasharma11** [comment]
Hey can I add the solution for DP-RodCuttingProblem?

**Comment by Trilokesh-Singh** [comment]
Hello Anurag.....

**Comment by Venoox** [comment]
Can I also add for Rust?

**Comment by Anuragkar234** [comment]
> Can I also add for Rust?

Just create a separate folder and add your files there.

**Comment by karankeyash** [comment]
It would be nice to have a list to keep track of.

**Comment by Anuragkar234** [comment]
Will be implementing soon!

**Comment by nidhi-bhanushali** [comment]
Can I add stack and queue implementation in python?

**Comment by anuragdevon** [comment]
Reopening this issue for ongoing hacktoberfest-2022, New PRs are accepted.

**Comment by omprakashchhetri** [comment]
Is there any DS topics that I can still work on?

**Comment by anuragdevon** [comment]
> Is there any DS topics that I can still work on? @anuragdevon

@omprakashchhetri Yes, You can check the repo and add the topics that are missing for particular language.

**Comment by omprakashchhetri** [comment]
Got it !! @anuragdevon

**Comment by omprakashchhetri** [comment]
hey I've just added my PR can you please check ! @anuragdevon

**Comment by KadhamVj23** [comment]
I want to work on it

**Comment by Code-Techy** [comment]
> Greetings , @anuragdevon 
**As a beginner to open source, I would like to contribute,
It would be a pleasure if you could assign me this issue since I have good experience with CPP programming.**

_-Regards, thanks._
